# Generated by Django 3.1.1 on 2020-09-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70)),
                ('pincode', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('userlocationname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentuser.location')),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=70)),
                ('like', models.CharField(max_length=70)),
                ('timing', models.CharField(max_length=70)),
                ('Resturantname', models.CharField(max_length=70)),
                ('locationname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentuser.location')),
            ],
        ),
    ]
